import type { Source } from "../../../operations/from";
import type { Exchange, ExchangeHeaders } from "../../../exchange";
import type { CraftContext } from "../../../context";
import type { EventName, EventPayload } from "../../../types";
import type { EventFilter } from "./types";

/**
 * Event source adapter that produces exchanges from framework events.
 * Subscribes to context events and emits them as exchanges.
 */
export class EventSourceAdapter implements Source<EventPayload<EventName>> {
  readonly adapterId = "routecraft.adapter.event";

  constructor(private filter: EventFilter) {}

  async subscribe(
    context: CraftContext,
    handler: (
      message: EventPayload<EventName>,
      headers?: ExchangeHeaders,
    ) => Promise<Exchange>,
    abortController: AbortController,
    onReady?: () => void,
  ): Promise<void> {
    const filters = Array.isArray(this.filter) ? this.filter : [this.filter];
    const unsubscribers: Array<() => void> = [];

    // Get the route ID from the first handler call (when onReady is called, we're part of a route)
    // This allows us to filter out events generated by this route to prevent infinite loops
    let initialized = false;
    const initializeRouteId = async () => {
      if (!initialized) {
        initialized = true;
        // Try to extract route ID from context if available
        // For now, we'll rely on checking the exchange/route details in the payload
      }
    };

    // Determine which events to subscribe to
    const eventNames = this.resolveEventNames(filters);

    context.logger.debug(
      { adapter: "event", filter: this.filter, eventNames },
      "Subscribing to events",
    );

    // Subscribe to each resolved event
    for (const eventName of eventNames) {
      const unsubscribe = context.on(
        eventName as EventName,
        async (payload) => {
          if (!abortController.signal.aborted) {
            // Initialize route ID on first event if needed
            await initializeRouteId();

            // Prevent infinite loops: don't process events from exchange/step lifecycle
            // These are generated when processing the event, causing feedback loops
            const isExchangeOrStepEvent =
              eventName.startsWith("exchange:") ||
              eventName.startsWith("step:");
            if (isExchangeOrStepEvent) {
              // Skip exchange and step events to prevent infinite loops
              return;
            }

            try {
              await handler(payload);
            } catch (error) {
              context.logger.error(
                { adapter: "event", event: eventName, err: error },
                "Event handler failed",
              );
            }
          }
        },
      );
      unsubscribers.push(unsubscribe);
    }

    // Cleanup on abort
    abortController.signal.addEventListener("abort", () => {
      context.logger.debug({ adapter: "event" }, "Unsubscribing from events");
      for (const unsubscribe of unsubscribers) {
        unsubscribe();
      }
    });

    onReady?.();

    // Keep the subscription alive until aborted
    return new Promise<void>((resolve) => {
      abortController.signal.addEventListener("abort", () => {
        resolve();
      });
    });
  }

  /**
   * Resolve event names from filters, expanding wildcards.
   */
  private resolveEventNames(filters: string[]): string[] {
    const allEventNames: EventName[] = [
      // Context events
      "context:starting",
      "context:started",
      "context:stopping",
      "context:stopped",
      // Route events
      "route:registered",
      "route:starting",
      "route:started",
      "route:stopping",
      "route:stopped",
      // Exchange events
      "exchange:started",
      "exchange:completed",
      "exchange:failed",
      // Step events
      "step:started",
      "step:completed",
      // System events
      "error",
    ];

    const resolved = new Set<string>();

    for (const filter of filters) {
      if (filter === "*") {
        // Match all events
        allEventNames.forEach((name) => resolved.add(name));
      } else if (filter.includes("*")) {
        // Wildcard pattern matching
        const pattern = this.wildcardToRegex(filter);
        for (const eventName of allEventNames) {
          if (pattern.test(eventName)) {
            resolved.add(eventName);
          }
        }
      } else {
        // Exact match
        resolved.add(filter);
      }
    }

    return Array.from(resolved);
  }

  /**
   * Convert wildcard pattern to regex.
   * Examples:
   * - 'route:*' -> /^route:.*$/
   * - 'exchange:*' -> /^exchange:.*$/
   * - 'route:myroute:*' -> /^route:myroute:.*$/
   */
  private wildcardToRegex(pattern: string): RegExp {
    const escaped = pattern
      .replace(/[.+?^${}()|[\]\\]/g, "\\$&") // Escape special regex chars
      .replace(/\*/g, ".*"); // Convert * to .*
    return new RegExp(`^${escaped}$`);
  }
}
