// Generated by scripts/generate-doc-layouts.mjs — do not edit by hand.
import { docMetadata } from '@/lib/doc-metadata'

const route = 'introduction/exchange'

export const metadata = docMetadata(route)

export default function DocLayout({ children }: { children: React.ReactNode }) {
  return children
}
