/** Behavioural mutants: name, file, pattern, replacement, and the test name expected to catch it. */
export const mutants: [string, string, string, string, string][] = [
  [
    "duplicate provider accepted",
    "host.ts",
    "c.plugins.length > 1",
    "false",
    "replacement under own identity",
  ],
  [
    "installation order breaks ties",
    "graph.ts",
    "a.id < b.id ? -1 : a.id > b.id ? 1 : 0",
    "0",
    "four handlers use selectors",
  ],
  [
    "concurrency reset per delivery",
    "operations.ts",
    "const max = Number",
    "active=0; const max = Number",
    "concurrency and breaker state",
  ],
  [
    "breaker reset per delivery",
    "operations.ts",
    "if (failures >= limit)",
    "if ((failures=0) >= limit)",
    "concurrency and breaker state",
  ],
  [
    "changed plan accepted",
    "runtime.ts",
    "saved.tail !== tailHash(route.steps, live)",
    "false",
    "defer → SIGKILL",
  ],
  [
    "fanout drops second child",
    "runtime.ts",
    "for (const child of outcome.exchanges)",
    "for (const child of outcome.exchanges.slice(0,1))",
    "runPaths isolates failures",
  ],
  [
    "handler decoration discarded",
    "runtime.ts",
    "ex = this.attach(wireExchange(result.exchange));",
    "ex = ex;",
    "four handlers use selectors",
  ],

  [
    "resume repeats prefix",
    "runtime.ts",
    "pending: live,",
    "pending: route.initial,",
    "defer → SIGKILL",
  ],
  [
    "defer fails to halt",
    "runtime.ts",
    "pending = []; break; } default:",
    "break; } default:",
    "defer → SIGKILL",
  ],
  [
    "reentrant instruction skipped",
    "runtime.ts",
    "const remaining = reenter ? [id, ...pending] : pending;",
    "const remaining = pending;",
    "defer → SIGKILL",
  ],
  [
    "CAS condition ignored",
    "storage.ts",
    "if((this.get(condition.key)?.version??0)!==condition.version)",
    "if(false)",
    "CAS under overlapping",
  ],
  [
    "transaction removed",
    "storage.ts",
    "this.db.exec('BEGIN IMMEDIATE')",
    "this.db.exec('SELECT 1')",
    "SIGKILL between record",
  ],
  [
    "delete is a read",
    "storage.ts",
    "DELETE FROM records WHERE key=?",
    "SELECT key FROM records WHERE key=?",
    "atomic store deletes",
  ],
  [
    "dependencies disposed first",
    "host.ts",
    "[...this.#applied].reverse()",
    "[...this.#applied]",
    "rollback and teardown",
  ],
  [
    "remaining cleanup skipped",
    "host.ts",
    "[...cleanup].reverse()",
    "[...cleanup].reverse().slice(0,1)",
    "rollback and teardown",
  ],
  [
    "observer failure escapes",
    "host.ts",
    "catch(e){this.faults.push(fault(observer.owner,'OBSERVER',e));}",
    "catch(e){throw e;}",
    "observers cannot abort",
  ],
  [
    "secondary error replaces primary",
    "runtime.ts",
    "error.secondary.push(failure);continue;",
    "throw failure;",
    "failing error handler",
  ],
  [
    "cancelled effect fence removed",
    "runtime.ts",
    "commit:(effect)=>{assertActive();return effect();}",
    "commit:(effect)=>effect()",
    "timeout cancels",
  ],
  [
    "resume admission skipped",
    "runtime.ts",
    'const ring = await this.handlers( spec, "admission", this.attach(door), "resume", undefined, view, );',
    'const ring = { kind: "allow" as const, exchange: this.attach(door), recorded: {} };',
    "resume rechecks admission",
  ],
  [
    "source never subscribed",
    "runtime.ts",
    "if(route.spec.source){",
    "if(false&&route.spec.source){",
    "source really emits",
  ],
  [
    "stream completion reported early",
    "runtime.ts",
    "const settled=await Promise.allSettled(streams);",
    "const settled=[];",
    "drain owns streaming",
  ],
  [
    "complete does not halt",
    "runtime.ts",
    "pending=[];ex=outcome.exchange;break;",
    "ex=outcome.exchange;break;",
    "continue, complete, drop",
  ],
  [
    "tag selector ignored",
    "runtime.ts",
    "(h.selector?.tag && !spec.tags.includes(h.selector.tag))",
    "false",
    "tag selector excludes",
  ],
  [
    "handler survival ignored",
    "runtime.ts",
    "!h.survival[kind] ||",
    "false ||",
    "declining resume",
  ],
  [
    "claimExpiry settles the record instead of claiming it",
    "storage.ts",
    "const value = { ...saved, claimedAt: at }; const won = await records.write( [ { key: `record/${id}`, value }, { key: `waiting/${id}`, value: index(value) }, ],",
    'const value = { ...saved, state: "expired" }; const won = await records.write([{ key: `record/${id}`, value }, { key: `waiting/${id}`, delete: true }],',
    "lease heals an expiry notification",
  ],
  [
    "claimExpiry ignores a live claim",
    "storage.ts",
    'if (!row || saved.state !== "waiting" || saved.claimedAt !== undefined) return "lost"; const value = { ...saved, claimedAt: at };',
    'if (!row || saved.state !== "waiting") return "lost"; const value = { ...saved, claimedAt: at };',
    "lease heals an expiry notification",
  ],
  [
    "releaseClaims ignores the lease deadline",
    "storage.ts",
    "if (!row || saved.claimedAt === undefined || saved.claimedAt > before)",
    "if (!row || saved.claimedAt === undefined || saved.claimedAt < before)",
    "lease heals an expiry notification",
  ],
  [
    "codec version ignored on resume",
    "runtime.ts",
    "if (saved.codec !== 2)",
    "if (false)",
    "codec and pending are checked",
  ],
  [
    "callable source not folded into the tail hash",
    "runtime.ts",
    'case "function": return Function.prototype.toString.call(value);',
    'case "function": return "fn";',
    "plan hash covers the tail",
  ],
  [
    "continuation id sequence not advanced",
    "runtime.ts",
    "const sequence = (Number(exchange.headers[DEFERRAL_SEQUENCE]) || 0) + 1;",
    "const sequence = 1;",
    "two defer points",
  ],
  [
    "resume without the compare-and-swap",
    "runtime.ts",
    "cas = await store.markResumed(id, now, by);",
    'cas = "won"; await store.markResumed(id, now, by);',
    "concurrent semantic resume",
  ],
  [
    "duplicate not answered from the cache",
    "runtime.ts",
    'if (record.state === "resumed") return this.duplicate(record);',
    "if (false) return this.duplicate(record);",
    "resume rechecks admission",
  ],
  [
    "failed resume not recorded",
    "runtime.ts",
    'store .recordOutcome(id, { status: "failed", exchanges: [], error: String(e), })',
    "Promise.resolve(void store)",
    "failed resume is recorded",
  ],
  [
    "duplicate deferral id accepted",
    "storage.ts",
    "[{ key: `record/${id}`, version: 0 }],",
    "[],",
    "second create under one id",
  ],
  [
    "sweep skips the expiry claim",
    "runtime.ts",
    'if ((await store.claimExpiry(entry.id, now)) !== "won") continue;',
    "await store.claimExpiry(entry.id, now);",
    "concurrent sweeps deliver one nag",
  ],
  [
    "defer boundary does not require plain JSON",
    "runtime.ts",
    "exchange: serialize(parked, owner),",
    "exchange: structuredClone({ id: parked.id, routeId: parked.routeId, body: parked.body, headers: parked.headers }),",
    "arbitrary in flight",
  ],
  [
    "drain never times out",
    "runtime.ts",
    "if (left <= 0) {",
    "if (false) {",
    "bounded time",
  ],
  [
    "observers receive the live event payload",
    "host.ts",
    "Object.freeze({ name, data: structuredClone(data) })",
    "Object.freeze({ name, data })",
    "observers see their own copy",
  ],
  [
    "branch identity check dropped",
    "runtime.ts",
    "known.execute !== s.execute",
    "false",
    "substitute a different function",
  ],
  [
    "duplicate anchors accepted",
    "host.ts",
    "if (anchors.has(x.anchor.key))",
    "if (false)",
    "claiming one anchor",
  ],
  [
    "step context require ignores declaration",
    "runtime.ts",
    "require: (contract) => this.host.requireFor(step.owner, contract),",
    "require: (contract) => this.host.service(contract),",
    "plugin's declaration",
  ],
  [
    "late disposer accepted",
    "host.ts",
    'if (this.#phase === "stopped" || this.#phase === "stopping") throw new Fault(plugin.id, "LIFECYCLE", "late disposer");',
    'if (false) throw new Fault(plugin.id, "LIFECYCLE", "late disposer");',
    "disposer registered during teardown",
  ],
  [
    "compile after start accepted",
    "runtime.ts",
    'if (this.#accept) throw new Fault(spec.owner, "FROZEN", "route compilation");',
    'if (false) throw new Fault(spec.owner, "FROZEN", "route compilation");',
    "compiled after start",
  ],
  [
    "dispatch inherits the caller's run kind",
    "runtime.ts",
    'exchange: { ...wireExchange(exchange), routeId }, kind: "normal",',
    "exchange: { ...wireExchange(exchange), routeId }, kind: run.kind,",
    "dispatch from a resumed run",
  ],
  [
    "route requirement unchecked (authorization fails open)",
    "runtime.ts",
    "if (!this.host.has(port))",
    "if (false)",
    "requires authority does not boot",
  ],
  [
    "refusal at exit silently ignored",
    "runtime.ts",
    "if (!descriptor.refuse) {",
    "if (false) {",
    "refusal at exit or error",
  ],
  [
    "option key namespace unchecked",
    "runtime.ts",
    'dot < 1 || (prefix !== "route" && !this.host.namespaces.has(prefix))',
    "false",
    "owner-qualified",
  ],
  [
    "facet may be named anything",
    "dsl.ts",
    "if (key !== namespaceOf(plugin))",
    "if (false)",
    "owner-qualified",
  ],
  [
    "duplicate namespace accepted",
    "host.ts",
    "if (namespaces.has(ns))",
    "if (false)",
    "owner-qualified",
  ],
  [
    "contribution ids collide across plugins",
    "host.ts",
    "(x) => x.owner === plugin.id && x.id === c.id,",
    "(x) => x.id === c.id,",
    "owner-qualified",
  ],
  [
    "nested child definitions omitted from the tail hash",
    "runtime.ts",
    "children: step.children?.map(describe) ?? [],",
    "children: [],",
    "edited child of a branching step",
  ],
  [
    "minted grant array not frozen",
    "auth.ts",
    "grants: Object.freeze([...principal.grants]),",
    "grants: [...principal.grants],",
    "minted principal is immutable",
  ],
  [
    "expiry scan ignores the deadline",
    "storage.ts",
    "if (entry.expiresAt > now) continue;",
    "",
    "orphaned record is skipped",
  ],
  [
    "markExpired settles an unclaimed record",
    "storage.ts",
    'if (!row || saved.state !== "waiting" || saved.claimedAt === undefined) return "lost";',
    'if (!row || saved.state !== "waiting") return "lost";',
    "denial, retention",
  ],
  [
    "duplicate drops the cached exchanges",
    "runtime.ts",
    "exchanges: record.outcome?.exchanges.map(revive) ?? [],",
    "exchanges: [],",
    "authorization refusal at the door",
  ],
  [
    "ingress headers merged into the continuation",
    "runtime.ts",
    "...ring.carry, [DEFERRAL_ID]: id,",
    "...ring.carry, ...ingress.headers, [DEFERRAL_ID]: id,",
    "keeps the parked identity restored",
  ],
  [
    "gate ignores the selected authority",
    "auth.ts",
    "const p = authority.principalOf(headers);",
    "const p = principalOf(headers);",
    "independently branded authority",
  ],
  [
    "facet ignores the selected authority",
    "auth.ts",
    "return { principal: authority.principalOf(ex.headers),",
    "return { principal: principalOf(ex.headers),",
    "independently branded authority",
  ],
  [
    "markResumed ignores a live claim",
    "storage.ts",
    'if (!row || saved.state !== "waiting" || saved.claimedAt !== undefined) return "lost"; const won = await records.write( [ { key: `record/${id}`, value: { ...saved, state: "resumed",',
    'if (!row || saved.state !== "waiting") return "lost"; const won = await records.write( [ { key: `record/${id}`, value: { ...saved, state: "resumed",',
    "notification claim excludes a resume",
  ],
  [
    "resume ignores the deadline",
    "runtime.ts",
    "if (saved.expiresAt !== undefined && saved.expiresAt <= now)",
    "if (false)",
    "arrives after the deadline",
  ],
  [
    "lifecycle disclosed before the door",
    "runtime.ts",
    'if (ring.kind !== "allow") return refused();',
    'if (ring.kind !== "allow") return record.state === "resumed" ? this.duplicate(record) : refused();',
    "duplicate passes admission",
  ],
  [
    "gate runs on the error channel",
    "auth.ts",
    "debounce: true, errorChannel: false,",
    "debounce: true, errorChannel: true,",
    "expiry on a protected route",
  ],
  [
    "expiry scan returns claimed records",
    "storage.ts",
    "if (!entry || entry.claimed || entry.expiresAt === null) continue;",
    "if (!entry || entry.expiresAt === null) continue;",
    "findExpired excludes claimed",
  ],
  [
    "orphan aborts the sweep",
    "runtime.ts",
    "orphans[entry.routeId] = (orphans[entry.routeId] ?? 0) + 1; continue;",
    'throw new Fault("kernel", "UNKNOWN_ROUTE", entry.routeId);',
    "orphaned record is skipped",
  ],
  [
    "unpersistable terminal body fails the resume",
    "runtime.ts",
    "exchanges.push(serialize(x, provider)); } catch { omitted++; }",
    "exchanges.push(serialize(x, provider)); } catch (e) { throw e; }",
    "unpersistable terminal body",
  ],
  [
    "nested source not projected",
    "runtime.ts",
    "for (const [k, v] of Object.entries(value as Record<string, unknown>)) out[k] = project(v, depth + 1);",
    'for (const [k, v] of Object.entries(value as Record<string, unknown>)) out[k] = typeof v === "function" ? "fn" : project(v, depth + 1);',
    "callback nested in a step",
  ],
  [
    "frame not anchored at the site",
    "runtime.ts",
    "push(at.list, at.index + (reenter ? 0 : 1));",
    "if (at.index + (reenter ? 0 : 1) < route.lists.get(at.list)!.length) push(at.list, at.index + (reenter ? 0 : 1));",
    "trailing defer point",
  ],
  [
    "exit decoration dropped from the result",
    "runtime.ts",
    'exchanges.push(exit.kind === "allow" ? exit.exchange : completed);',
    "exchanges.push(completed);",
    "exit decoration reaches",
  ],
  [
    "point policy ignored for an external point",
    "runtime.ts",
    'if (!descriptor) throw new Fault("kernel", "UNKNOWN_POINT", String(point));',
    'if (!descriptor) throw new Fault("kernel", "UNKNOWN_POINT", String(point)); if (!(point in { admission: 1, entry: 1, error: 1, exit: 1 })) return exchange;',
    "external point's refusal policy",
  ],
  [
    "undeclared point accepted at bind",
    "host.ts",
    'if (c.kind === "handler" && !this.points.has(c.point))',
    "if (false)",
    "external point's refusal policy",
  ],
  [
    "stranded residue not reported at boot",
    "storage.ts",
    "const stranded = await store.resumedWithoutOutcome(100);",
    "const stranded: string[] = [];",
    "boot scans the store",
  ],
  [
    "boot sweep skips healing",
    "storage.ts",
    "const sweep = () => ctx.execution.sweep({ lease, retention });",
    "const sweep = () => ctx.execution.sweep({ retention });",
    "boot scans the store",
  ],
  [
    "step state leaks into the next deferral",
    "runtime.ts",
    "remaining, outcome.request, step.owner,",
    "remaining, outcome.request.state !== undefined ? outcome.request : { ...outcome.request, state: run.resumption?.stepState }, step.owner,",
    "does not leak into the next deferral",
  ],
  [
    "mismatch leaves the record resumable",
    "runtime.ts",
    'if (how === "expired") await store.markExpired(id, now); else await store.markDenied(id, now, reason);',
    'if (how === "expired") await store.markExpired(id, now); else await store.releaseClaims(now);',
    "nested in a step's declared source",
  ],
  [
    "a refused resume spends the approval",
    "runtime.ts",
    'if (ring.kind !== "allow") return refused();',
    'if (ring.kind !== "allow") { await store.markResumed(id, Date.now()); return refused(); }',
    "authorization refusal at the door",
  ],
  [
    "empty ask admits anyone",
    "auth.ts",
    'if (!required) return { kind: "allow", exchange: ex };',
    'if (!required || required.length === 0) return { kind: "allow", exchange: ex };',
    "F1:",
  ],
  [
    "resumer reference not recorded by the door",
    "auth.ts",
    "record: { resumedBy: authority.refOf(ex.headers) },",
    "record: {},",
    "F2, F3:",
  ],
  [
    "resumer not written by the swap",
    "runtime.ts",
    "cas = await store.markResumed(id, now, by);",
    "cas = await store.markResumed(id, now);",
    "F2, F3:",
  ],
  [
    "secret rule removed",
    "codec.ts",
    'if (secrets.has(object)) throw refuse(owner, path, "a secret");',
    "",
    "F2, F3:",
  ],
  [
    "door handed the parked body",
    "runtime.ts",
    "payload: ingress.payload, ...(ingress.signal ? { signal: ingress.signal } : {}), };",
    "payload: ingress.payload, body: saved.exchange.body, ...(ingress.signal ? { signal: ingress.signal } : {}), };",
    "F4, F5:",
  ],
  [
    "route resolved before the door",
    "runtime.ts",
    "const known = this.#routes.get(saved.routeId);",
    "const known = this.route(saved.routeId);",
    "F4, F5:",
  ],
  [
    "deadline not rechecked after the swap",
    "runtime.ts",
    "if (saved.expiresAt !== undefined && saved.expiresAt <= Date.now()) {",
    "if (false) {",
    "F6:",
  ],
  [
    "nested path may park",
    "runtime.ts",
    'if (run.nested) throw new Fault(step.owner, "DEFER_IN_PATH", id);',
    "",
    "F7:",
  ],
  [
    "frames ignore a bounded slice",
    "runtime.ts",
    "from + run < ids.length ? { list, from, to: from + run } : { list, from },",
    "{ list, from },",
    "F8:",
  ],
  [
    "codec accumulates on Object.prototype",
    "codec.ts",
    "Object.create(null) as Record< string, unknown >; for (const key of names) {",
    "{} as Record<string, unknown>; for (const key of names) {",
    "F9, F10:",
  ],
  [
    "decode assigns __proto__",
    "codec.ts",
    "Object.defineProperty(out, key, { value: decode(record[key], `${path}.${key}`), enumerable: true, writable: true, configurable: true, });",
    "out[key] = decode(record[key], `${path}.${key}`);",
    "G13, G14",
  ],
  [
    "symbol-keyed property accepted",
    "codec.ts",
    'if (Object.getOwnPropertySymbols(object).length) throw refuse(owner, path, "a symbol-keyed property");',
    "",
    "F9, F10:",
  ],
  [
    "non-enumerable property accepted",
    "codec.ts",
    "if (!Object.prototype.propertyIsEnumerable.call(object, name)) throw refuse(owner, path, `a non-enumerable property (${name})`);",
    "",
    "F9, F10:",
  ],
  [
    "named array property accepted",
    "codec.ts",
    "if (named.length) throw refuse(owner, path, `a named array property (${named[0]})`);",
    "",
    "F9, F10:",
  ],
  [
    "Date subclass accepted",
    "codec.ts",
    'if (Object.getPrototypeOf(object) !== Date.prototype) throw refuse(owner, path, "a Date subclass");',
    "",
    "F9, F10:",
  ],
  [
    "Date with properties accepted",
    "codec.ts",
    'if (Object.getOwnPropertyNames(object).length) throw refuse(owner, path, "a Date carrying extra properties");',
    "",
    "F9, F10:",
  ],
  [
    "reserved envelope accepted as data",
    "codec.ts",
    'if (names.length === 1 && names[0] === DATE_TAG) throw refuse(owner, path, "the reserved date envelope");',
    "",
    "F9, F10:",
  ],
  [
    "corrupt envelope revived",
    "codec.ts",
    "if (Number.isNaN(revived.getTime()))",
    "if (false)",
    "F9, F10:",
  ],
  [
    "non-finite number accepted",
    "codec.ts",
    'if (!Number.isFinite(value)) throw refuse(owner, path, "a non-finite number");',
    "",
    "F9, F10:",
  ],
  [
    "symbol value dropped silently",
    "codec.ts",
    'case "symbol": throw refuse(owner, path, "a symbol");',
    'case "symbol": return undefined;',
    "F9, F10:",
  ],
  [
    "cycle check removed",
    "codec.ts",
    'if (seen.has(object)) throw refuse(owner, path, "a cycle");',
    "",
    "F9, F10:",
  ],
  [
    "boot report reads the plugin's own store",
    "storage.ts",
    "const store = ctx.require(CONTINUATIONS);",
    "const store = durableStore(ctx.require(RECORDS));",
    "F11:",
  ],
  [
    "sweep abandoned when stop begins",
    "runtime.ts",
    "if (!this.#accept && !this.#draining)",
    "if (!this.#accept)",
    "F12: a record claimed",
  ],
  [
    "default ttl not applied",
    "storage.ts",
    "ttl = options.ttl === undefined ? DEFAULT_TTL : options.ttl;",
    "ttl = options.ttl ?? null;",
    "F14:",
  ],
  [
    "door hook ignored",
    "auth.ts",
    'if (!verdict.ok || verdict.value !== true) return refuse("door refused the resumer");',
    "",
    "ruling 13:",
  ],
  [
    "default door policy skipped",
    "auth.ts",
    "const verdict = enforcement.check(ex.headers, required); if (verdict) return refuse(verdict.reason, verdict.missing); } let carry",
    "} let carry",
    "ruling 13:",
  ],
  [
    "elevation may change identity",
    "auth.ts",
    "view.subject !== input.deferred.subject ||",
    "false ||",
    "step-up:",
  ],
  [
    "lend unbounded",
    "auth.ts",
    "const overreach = view.lent.filter((g) => !bound.has(g));",
    "const overreach: string[] = [];",
    "step-up:",
  ],
  [
    "elevation need not be live",
    "auth.ts",
    'if (!view?.authentic) return refuse("elevation is not a live principal");',
    'if (!view) return refuse("elevation is not a live principal");',
    "step-up:",
  ],
  [
    "carry ignored",
    "auth.ts",
    "carry = elevated.value;",
    "carry = undefined;",
    "step-up:",
  ],
  [
    "park from a refusal loses the bound",
    "runtime.ts",
    "refusal.detail = admitted.detail;",
    "",
    "step-up:",
  ],
  [
    "notify before the record is durable",
    "runtime.ts",
    'try { await store.create(id, saved); } catch (e) { throw fault(provider, "PARK", e); }',
    'if (request.notify) await request.notify(id); try { await store.create(id, saved); } catch (e) { throw fault(provider, "PARK", e); }',
    "step-up:",
  ],
  [
    "event before notify",
    "runtime.ts",
    "if (request.notify) try { await request.notify(id); } catch (e) {",
    'this.host.emit("exchange:deferred", { id, route: route.spec.id }); if (request.notify) try { await request.notify(id); } catch (e) {',
    "step-up:",
  ],
  [
    "undeclared park accepted",
    "runtime.ts",
    "if (!descriptor.defer || !h.mayDefer) {",
    "if (!descriptor.defer) {",
    "error-path park:",
  ],
  [
    "error-path park restarts the route",
    "runtime.ts",
    "site.step, true, [site.step, ...site.pending],",
    "null, false, route.initial,",
    "error-path park:",
  ],
  [
    "sweep stops at the first page",
    "runtime.ts",
    "if (page.length < pageSize) break;",
    "break;",
    "sweep as wired:",
  ],
  [
    "orphan does not advance the cursor",
    "runtime.ts",
    "cursor = entry; visited++; const route = this.#routes.get(entry.routeId); if (!route) {",
    "visited++; const route = this.#routes.get(entry.routeId); if (!route) {",
    "sweep as wired:",
  ],
  [
    "sweep never purges",
    "runtime.ts",
    "? await store.purgeSettled(now - retention) : 0;",
    "? 0 : 0;",
    "sweep as wired:",
  ],
  [
    "sweep releases live claims",
    "runtime.ts",
    "? await store.releaseClaims(now - lease) : 0;",
    "? await store.releaseClaims(now) : 0;",
    "sweep as wired:",
  ],
  [
    "settle reports expiry after a winning resume",
    "runtime.ts",
    'if (settled?.state === "resumed") return this.duplicate(settled); throw error;',
    "throw error;",
    "resume path branches:",
  ],
  [
    "claimed record proceeds",
    "runtime.ts",
    'if (record.state !== "waiting" || record.claimedAt !== undefined)',
    'if (record.state !== "waiting")',
    "resume path branches:",
  ],
  [
    "lent grants not honoured",
    "auth.ts",
    "const held = new Set([...p.grants, ...p.lent]);",
    "const held = new Set([...p.grants]);",
    "resume path branches:",
  ],
  [
    "duplicate route id accepted",
    "runtime.ts",
    'if (this.#routes.has(spec.id)) throw new Fault(spec.owner, "DUPLICATE_ROUTE", spec.id);',
    'if (false) throw new Fault(spec.owner, "DUPLICATE_ROUTE", spec.id);',
    "resume path branches:",
  ],
  [
    "resumedAt header dropped",
    "runtime.ts",
    "[DEFERRAL_RESUMED_AT]: now,",
    "",
    "resume path branches:",
  ],
  [
    "stranded report unbounded",
    "storage.ts",
    "const stranded = await store.resumedWithoutOutcome(100);",
    "const stranded = await store.resumedWithoutOutcome();",
    "resume path branches:",
  ],
  [
    "scan stall undetected",
    "runtime.ts",
    'throw new Fault(provider, "SCAN_STALLED", `${entry.id} is not after ${previous.id}`);',
    "break;",
    "does not advance past the cursor",
  ],
  [
    "no re-check after the door",
    "runtime.ts",
    'if (!this.#accept) throw new Fault("kernel", "NOT_RUNNING", "resume"); let by: unknown;',
    "let by: unknown;",
    "G8, G9:",
  ],
  [
    "resume not owned work",
    "runtime.ts",
    "return this.own(this.runResume(id, ingress));",
    "return this.runResume(id, ingress);",
    "G8, G9:",
  ],
  [
    "re-admission skipped for a door park",
    "runtime.ts",
    "} else if (resume.site === null) {",
    "} else if (false) {",
    "G1:",
  ],
  [
    "cancelled run parked",
    "runtime.ts",
    'if (run.signal.aborted) return decline("DEFER_CANCELLED", "the run was cancelled");',
    "",
    "G11:",
  ],
  [
    "site-less failure parked from the top",
    "runtime.ts",
    "if (!site && !refusal)",
    "if (false)",
    "G3:",
  ],
  [
    "repeated park allowed",
    "runtime.ts",
    "this.host.namespaceFor(refusal.owner) in resume.refusal",
    "false",
    "G7:",
  ],
  [
    "failed notify leaves a live link",
    "runtime.ts",
    'if ((await store.claimExpiry(id, now)) === "won") await store.markDenied(id, now, "notify failed");',
    "",
    "G12:",
  ],
  [
    "store default ttl ignored",
    "runtime.ts",
    "const ttl = request.ttl ?? store.defaults?.ttl;",
    "const ttl = request.ttl;",
    "G10:",
  ],
  [
    "bound not namespaced",
    "runtime.ts",
    "[this.host.namespaceFor(refusal.owner)]: encode(",
    '["auth"]: encode(',
    "G2:",
  ],
  [
    "hook throw is an oracle",
    "auth.ts",
    "return { ok: true, value }; } catch { return { ok: false }; }",
    "return { ok: true, value }; } catch (e) { throw e; }",
    "G8, G9:",
  ],
  [
    "hook not bounded by the ingress signal",
    "auth.ts",
    'signal?.addEventListener("abort", abort, { once: true });',
    "",
    "G8, G9:",
  ],
  [
    "-0 kept",
    "codec.ts",
    "return Object.is(value, -0) ? 0 : value;",
    "return value;",
    "G13, G14",
  ],
  [
    "defer inside a fan-out parked",
    "runtime.ts",
    'if (item.fanned) throw new Fault(step.owner, "DEFER_IN_FANOUT", id);',
    "",
    "G4, G5",
  ],
  [
    "fan-out child failure carries a site",
    "runtime.ts",
    "if (!run.nested && !item.fanned && !f.site)",
    "if (!run.nested && !f.site)",
    "G4, G5",
  ],
  [
    "elevation's grant ring not compared",
    "auth.ts",
    "[...view.grants].sort().join() !== [...input.deferred.grants].sort().join()",
    "false",
    "survivors:",
  ],
  [
    "parked lent grants dropped from the bound",
    "auth.ts",
    "...(input.deferred?.lent ?? []),",
    "",
    "survivors:",
  ],
  [
    "step state handed to every step",
    "runtime.ts",
    "...(run.resumption?.site === id ? { stepState: run.resumption.stepState } : {}),",
    "...(run.resumption ? { stepState: run.resumption.stepState } : {}),",
    "survivors:",
  ],
  [
    "sweep ignores a stop between records",
    "runtime.ts",
    "for (const entry of page) { if (!this.#accept) break;",
    "for (const entry of page) {",
    "survivors:",
  ],
  [
    "sweep ignores a stop between pages",
    "runtime.ts",
    "for (;;) { if (!this.#accept) break; const page",
    "for (;;) { const page",
    "survivors:",
  ],
  [
    "a step failure records a bound",
    "runtime.ts",
    'failure.code === "REFUSED" ? { owner: failure.plugin, detail: failure.detail } : undefined;',
    "{ owner: failure.plugin, detail: failure.detail };",
    "error-path park:",
  ],
];
