/** Behavioural mutants: name, file, pattern, replacement, and the test name expected to catch it. */
export const mutants: [string, string, string, string, string][] = [
  [
    "duplicate provider accepted",
    "host.ts",
    "c.plugins.length > 1",
    "false",
    "replacement under own identity",
  ],
  [
    "installation order breaks ties",
    "graph.ts",
    "a.id < b.id ? -1 : a.id > b.id ? 1 : 0",
    "0",
    "four handlers use selectors",
  ],
  [
    "concurrency reset per delivery",
    "operations.ts",
    "const max = Number",
    "active=0; const max = Number",
    "concurrency and breaker state",
  ],
  [
    "breaker reset per delivery",
    "operations.ts",
    "if (failures >= limit)",
    "if ((failures=0) >= limit)",
    "concurrency and breaker state",
  ],
  [
    "changed plan accepted",
    "runtime.ts",
    "saved.tail !== tailHash(route.steps, live)",
    "false",
    "defer → SIGKILL",
  ],
  [
    "fanout drops second child",
    "runtime.ts",
    "for (const child of outcome.exchanges)",
    "for (const child of outcome.exchanges.slice(0,1))",
    "runPaths isolates failures",
  ],
  [
    "handler decoration discarded",
    "runtime.ts",
    "ex = this.attach(wireExchange(result.exchange));",
    "ex = ex;",
    "four handlers use selectors",
  ],

  [
    "resume repeats prefix",
    "runtime.ts",
    "pending: live,",
    "pending: route.initial,",
    "defer → SIGKILL",
  ],
  [
    "defer fails to halt",
    "runtime.ts",
    "deferrals.push(continuationId);pending=[]",
    "deferrals.push(continuationId)",
    "defer → SIGKILL",
  ],
  [
    "reentrant instruction skipped",
    "runtime.ts",
    "const remaining = reenter ? [id, ...pending] : pending;",
    "const remaining = pending;",
    "defer → SIGKILL",
  ],
  [
    "CAS condition ignored",
    "storage.ts",
    "if((this.get(condition.key)?.version??0)!==condition.version)",
    "if(false)",
    "CAS under overlapping",
  ],
  [
    "transaction removed",
    "storage.ts",
    "this.db.exec('BEGIN IMMEDIATE')",
    "this.db.exec('SELECT 1')",
    "SIGKILL between record",
  ],
  [
    "delete is a read",
    "storage.ts",
    "DELETE FROM records WHERE key=?",
    "SELECT key FROM records WHERE key=?",
    "atomic store deletes",
  ],
  [
    "dependencies disposed first",
    "host.ts",
    "[...this.#applied].reverse()",
    "[...this.#applied]",
    "rollback and teardown",
  ],
  [
    "remaining cleanup skipped",
    "host.ts",
    "[...cleanup].reverse()",
    "[...cleanup].reverse().slice(0,1)",
    "rollback and teardown",
  ],
  [
    "observer failure escapes",
    "host.ts",
    "catch(e){this.faults.push(fault(observer.owner,'OBSERVER',e));}",
    "catch(e){throw e;}",
    "observers cannot abort",
  ],
  [
    "secondary error replaces primary",
    "runtime.ts",
    "error.secondary.push(failure);continue;",
    "throw failure;",
    "failing error handler",
  ],
  [
    "cancelled effect fence removed",
    "runtime.ts",
    "commit:(effect)=>{assertActive();return effect();}",
    "commit:(effect)=>effect()",
    "timeout cancels",
  ],
  [
    "resume admission skipped",
    "runtime.ts",
    'const admitted = await this.handlers( route, "admission", this.attach(door), "resume", undefined, { id, deferred: saved.exchange }, );',
    "const admitted = this.attach(door);",
    "resume rechecks admission",
  ],
  [
    "source never subscribed",
    "runtime.ts",
    "if(route.spec.source){",
    "if(false&&route.spec.source){",
    "source really emits",
  ],
  [
    "stream completion reported early",
    "runtime.ts",
    "const settled=await Promise.allSettled(streams);",
    "const settled=[];",
    "drain owns streaming",
  ],
  [
    "complete does not halt",
    "runtime.ts",
    "pending=[];ex=outcome.exchange;break;",
    "ex=outcome.exchange;break;",
    "continue, complete, drop",
  ],
  [
    "tag selector ignored",
    "runtime.ts",
    "(h.selector?.tag && !route.spec.tags.includes(h.selector.tag))",
    "false",
    "tag selector excludes",
  ],
  [
    "handler survival ignored",
    "runtime.ts",
    "!h.survival[kind] ||",
    "false ||",
    "declining resume",
  ],
  [
    "claimExpiry settles the record instead of claiming it",
    "storage.ts",
    "const value = { ...saved, claimedAt: at }; const won = await records.write( [ { key: `record/${id}`, value }, { key: `waiting/${id}`, value: index(value) }, ],",
    'const value = { ...saved, state: "expired" }; const won = await records.write([{ key: `record/${id}`, value }, { key: `waiting/${id}`, delete: true }],',
    "lease heals an expiry notification",
  ],
  [
    "claimExpiry ignores a live claim",
    "storage.ts",
    'if (!row || saved.state !== "waiting" || saved.claimedAt !== undefined) return "lost"; const value = { ...saved, claimedAt: at };',
    'if (!row || saved.state !== "waiting") return "lost"; const value = { ...saved, claimedAt: at };',
    "lease heals an expiry notification",
  ],
  [
    "releaseClaims ignores the lease deadline",
    "storage.ts",
    "if (!row || saved.claimedAt === undefined || saved.claimedAt > before)",
    "if (!row || saved.claimedAt === undefined || saved.claimedAt < before)",
    "lease heals an expiry notification",
  ],
  [
    "codec version ignored on resume",
    "runtime.ts",
    "const live = saved.codec === 2 ? pendingOf(route, saved.frames) : undefined;",
    "const live = pendingOf(route, saved.frames);",
    "codec and pending are checked",
  ],
  [
    "callable source not folded into the tail hash",
    "runtime.ts",
    'case "function": return Function.prototype.toString.call(value);',
    'case "function": return "fn";',
    "plan hash covers the tail",
  ],
  [
    "continuation id sequence not advanced",
    "runtime.ts",
    "(Number(outcome.exchange.headers[DEFERRAL_SEQUENCE]) || 0) + 1;",
    "1;",
    "two defer points",
  ],
  [
    "resume without the compare-and-swap",
    "runtime.ts",
    "cas = await store.markResumed(id, now);",
    'cas = "won"; await store.markResumed(id, now);',
    "concurrent semantic resume",
  ],
  [
    "duplicate not answered from the cache",
    "runtime.ts",
    'if (record.state === "resumed") return this.duplicate(record);',
    "if (false) return this.duplicate(record);",
    "resume rechecks admission",
  ],
  [
    "failed resume not recorded",
    "runtime.ts",
    'store .recordOutcome(id, { status: "failed", exchanges: [], error: String(e), })',
    "Promise.resolve(void store)",
    "failed resume is recorded",
  ],
  [
    "duplicate deferral id accepted",
    "storage.ts",
    "[{ key: `record/${id}`, version: 0 }],",
    "[],",
    "second create under one id",
  ],
  [
    "sweep skips the expiry claim",
    "runtime.ts",
    'if ((await store.claimExpiry(entry.id, now)) !== "won") continue;',
    "await store.claimExpiry(entry.id, now);",
    "concurrent sweeps deliver one nag",
  ],
  [
    "defer boundary does not require plain JSON",
    "runtime.ts",
    "exchange: serialize(parked, step.owner),",
    "exchange: structuredClone({ id: parked.id, routeId: parked.routeId, body: parked.body, headers: parked.headers }),",
    "arbitrary in flight",
  ],
  [
    "drain never times out",
    "runtime.ts",
    "if (left <= 0) {",
    "if (false) {",
    "bounded time",
  ],
  [
    "observers receive the live event payload",
    "host.ts",
    "Object.freeze({ name, data: structuredClone(data) })",
    "Object.freeze({ name, data })",
    "observers see their own copy",
  ],
  [
    "branch identity check dropped",
    "runtime.ts",
    "known.execute !== s.execute",
    "false",
    "substitute a different function",
  ],
  [
    "duplicate anchors accepted",
    "host.ts",
    "if (anchors.has(x.anchor.key))",
    "if (false)",
    "claiming one anchor",
  ],
  [
    "step context require ignores declaration",
    "runtime.ts",
    "require: (contract) => this.host.requireFor(step.owner, contract),",
    "require: (contract) => this.host.service(contract),",
    "plugin's declaration",
  ],
  [
    "late disposer accepted",
    "host.ts",
    'if (this.#phase === "stopped" || this.#phase === "stopping") throw new Fault(plugin.id, "LIFECYCLE", "late disposer");',
    'if (false) throw new Fault(plugin.id, "LIFECYCLE", "late disposer");',
    "disposer registered during teardown",
  ],
  [
    "compile after start accepted",
    "runtime.ts",
    'if (this.#accept) throw new Fault(spec.owner, "FROZEN", "route compilation");',
    'if (false) throw new Fault(spec.owner, "FROZEN", "route compilation");',
    "compiled after start",
  ],
  [
    "dispatch inherits the caller's run kind",
    "runtime.ts",
    'exchange: { ...wireExchange(exchange), routeId }, kind: "normal",',
    "exchange: { ...wireExchange(exchange), routeId }, kind: run.kind,",
    "dispatch from a resumed run",
  ],
  [
    "route requirement unchecked (authorization fails open)",
    "runtime.ts",
    "if (!this.host.has(port))",
    "if (false)",
    "requires authority does not boot",
  ],
  [
    "refusal at exit silently ignored",
    "runtime.ts",
    "if (!descriptor.refuse) {",
    "if (false) {",
    "refusal at exit or error",
  ],
  [
    "option key namespace unchecked",
    "runtime.ts",
    'dot < 1 || (prefix !== "route" && !this.host.namespaces.has(prefix))',
    "false",
    "owner-qualified",
  ],
  [
    "facet may be named anything",
    "dsl.ts",
    "if (key !== namespaceOf(plugin))",
    "if (false)",
    "owner-qualified",
  ],
  [
    "duplicate namespace accepted",
    "host.ts",
    "if (namespaces.has(ns))",
    "if (false)",
    "owner-qualified",
  ],
  [
    "contribution ids collide across plugins",
    "host.ts",
    "(x) => x.owner === plugin.id && x.id === c.id,",
    "(x) => x.id === c.id,",
    "owner-qualified",
  ],
  [
    "nested child definitions omitted from the tail hash",
    "runtime.ts",
    "children: step.children?.map(describe) ?? [],",
    "children: [],",
    "edited child of a branching step",
  ],
  [
    "minted grant array not frozen",
    "auth.ts",
    "grants: Object.freeze([...principal.grants]),",
    "grants: [...principal.grants],",
    "minted principal is immutable",
  ],
  [
    "expiry scan ignores the deadline",
    "storage.ts",
    "if (entry.expiresAt > now) continue;",
    "",
    "orphaned record is skipped",
  ],
  [
    "markExpired settles an unclaimed record",
    "storage.ts",
    'if (!row || saved.state !== "waiting" || saved.claimedAt === undefined) return "lost";',
    'if (!row || saved.state !== "waiting") return "lost";',
    "denial, retention",
  ],
  [
    "duplicate drops the cached exchanges",
    "runtime.ts",
    "exchanges: record.outcome?.exchanges.map(revive) ?? [],",
    "exchanges: [],",
    "authorization refusal at the door",
  ],
  [
    "ingress headers merged into the continuation",
    "runtime.ts",
    "headers: { ...parked.headers, [DEFERRAL_RESULT]: ingress.payload,",
    "headers: { ...parked.headers, ...admitted.headers, [DEFERRAL_RESULT]: ingress.payload,",
    "keeps the parked identity restored",
  ],
  [
    "gate ignores the selected authority",
    "auth.ts",
    "const p = authority.principalOf(headers);",
    "const p = principalOf(headers);",
    "independently branded authority",
  ],
  [
    "facet ignores the selected authority",
    "auth.ts",
    "principal: authority.principalOf(ex.headers),",
    "principal: principalOf(ex.headers),",
    "independently branded authority",
  ],
  [
    "markResumed ignores a live claim",
    "storage.ts",
    'if (!row || saved.state !== "waiting" || saved.claimedAt !== undefined) return "lost"; const won = await records.write( [ { key: `record/${id}`, value: { ...saved, state: "resumed", resumedAt: at, settledAt: at }, },',
    'if (!row || saved.state !== "waiting") return "lost"; const won = await records.write( [ { key: `record/${id}`, value: { ...saved, state: "resumed", resumedAt: at, settledAt: at }, },',
    "notification claim excludes a resume",
  ],
  [
    "resume ignores the deadline",
    "runtime.ts",
    "if (saved.expiresAt !== undefined && saved.expiresAt <= now)",
    "if (false)",
    "arrives after the deadline",
  ],
  [
    "lifecycle disclosed before the door",
    "runtime.ts",
    'if (!admitted) return { status: "refused", exchanges: [], deferrals: [] };',
    'if (!admitted) return record.state === "resumed" ? this.duplicate(record) : { status: "refused", exchanges: [], deferrals: [] };',
    "duplicate passes admission",
  ],
  [
    "gate runs on the error channel",
    "auth.ts",
    "errorChannel: false,",
    "errorChannel: true,",
    "expiry on a protected route",
  ],
  [
    "expiry scan returns claimed records",
    "storage.ts",
    "if (!entry || entry.claimed || entry.expiresAt === null) continue;",
    "if (!entry || entry.expiresAt === null) continue;",
    "findExpired excludes claimed",
  ],
  [
    "orphan aborts the sweep",
    "runtime.ts",
    "orphans[entry.routeId] = (orphans[entry.routeId] ?? 0) + 1; continue;",
    'throw new Fault("kernel", "UNKNOWN_ROUTE", entry.routeId);',
    "orphaned record is skipped",
  ],
  [
    "unpersistable terminal body fails the resume",
    "runtime.ts",
    "exchanges.push(serialize(x, provider)); } catch { omitted++; }",
    "exchanges.push(serialize(x, provider)); } catch (e) { throw e; }",
    "unpersistable terminal body",
  ],
  [
    "nested source not projected",
    "runtime.ts",
    "for (const [k, v] of Object.entries(value as Record<string, unknown>)) out[k] = project(v, depth + 1);",
    'for (const [k, v] of Object.entries(value as Record<string, unknown>)) out[k] = typeof v === "function" ? "fn" : project(v, depth + 1);',
    "callback nested in a step",
  ],
  [
    "frame not anchored at the site",
    "runtime.ts",
    "if (i >= remaining.length) return frames;",
    "if (i >= remaining.length) return frames.filter((f) => route.lists.get(f.list)!.length > f.from);",
    "trailing defer point",
  ],
  [
    "exit decoration dropped from the result",
    "runtime.ts",
    '(await this.handlers(route, "exit", completed, run.kind)) ?? completed,',
    '(await this.handlers(route, "exit", completed, run.kind), completed),',
    "exit decoration reaches",
  ],
  [
    "point policy ignored for an external point",
    "runtime.ts",
    'if (!descriptor) throw new Fault("kernel", "UNKNOWN_POINT", String(point));',
    'if (!descriptor) throw new Fault("kernel", "UNKNOWN_POINT", String(point)); if (!(point in { admission: 1, entry: 1, error: 1, exit: 1 })) return exchange;',
    "external point's refusal policy",
  ],
  [
    "undeclared point accepted at bind",
    "host.ts",
    'if (c.kind === "handler" && !this.points.has(c.point))',
    "if (false)",
    "external point's refusal policy",
  ],
  [
    "stranded residue not reported at boot",
    "storage.ts",
    "const stranded = await store.resumedWithoutOutcome(100);",
    "const stranded: string[] = [];",
    "boot scans the store",
  ],
  [
    "boot sweep skips healing",
    "storage.ts",
    "const sweep = () => ctx.execution.sweep({ lease, retention });",
    "const sweep = () => ctx.execution.sweep({ retention });",
    "boot scans the store",
  ],
  [
    "step state leaks into the next deferral",
    "runtime.ts",
    '...(outcome.request.state !== undefined ? { stepState: encode( outcome.request.state, step.owner, "stepState", ), } : {}),',
    '...(outcome.request.state !== undefined ? { stepState: encode( outcome.request.state, step.owner, "stepState", ), } : run.resumption?.stepState !== undefined ? { stepState: run.resumption.stepState } : {}),',
    "does not leak into the next deferral",
  ],
  [
    "mismatch leaves the record resumable",
    "runtime.ts",
    'if (how === "expired") await store.markExpired(id, now); else await store.markDenied(id, now, reason);',
    'if (how === "expired") await store.markExpired(id, now); else await store.releaseClaims(now);',
    "nested in a step's declared source",
  ],
  [
    "a refused resume spends the approval",
    "runtime.ts",
    'if (!admitted) return { status: "refused", exchanges: [], deferrals: [] };',
    'if (!admitted) { await store.markResumed(id, Date.now()); return { status: "refused", exchanges: [], deferrals: [] }; }',
    "authorization refusal at the door",
  ],
];
