import type { StandardSchemaV1 } from "@standard-schema/spec";
import type { Source, Destination } from "@routecraft/routecraft";
import { CliSourceAdapter } from "./source.ts";
import { CliDestinationAdapter } from "./destination.ts";
import type { CliServerOptions } from "./types.ts";

/**
 * Creates a CLI adapter for exposing routecraft routes as CLI commands.
 *
 * When used as a **source** (`.from()`), each call defines one CLI command.
 * Schema properties become named flags (`--flag-name <value>`), with native
 * CLI features (aliases, env fallback, positional args) configurable via
 * `flags` and `args` options. Help text is auto-generated by commander.
 *
 * The adapter is self-sufficient: it handles help printing, unknown-command
 * errors, flag parsing, validation, and dispatch internally. No external
 * runner needs to know about CLI-specific logic.
 *
 * Use `cli.stdout()` and `cli.stderr()` as destinations to write output.
 *
 * @param command - Command name as it appears on the CLI (e.g. `"greet"`)
 * @param options - Command options: `schema`, `description`, `flags`, `args`, `examples`
 * @returns A `Source` that fires once when the named command is invoked
 *
 * @example
 * ```typescript
 * import { craft } from '@routecraft/routecraft';
 * import { cli } from '@routecraft/os';
 * import { z } from 'zod';
 *
 * export default [
 *   craft().id('greet')
 *     .from(cli('greet', {
 *       schema: z.object({ name: z.string(), loud: z.boolean().optional() }),
 *       description: 'Greet someone',
 *       flags: { name: { alias: 'n', env: 'GREET_NAME' }, loud: { alias: 'l' } },
 *       examples: ['greet --name Alice', 'greet -n Bob --loud'],
 *     }))
 *     .transform(({ name, loud }) =>
 *       loud ? `HELLO ${name.toUpperCase()}!` : `Hello, ${name}!`
 *     )
 *     .to(cli.stdout()),
 * ];
 * ```
 *
 * @experimental
 */
export function cli<S extends StandardSchemaV1>(
  command: string,
  options: CliServerOptions & { schema: S },
): Source<StandardSchemaV1.InferOutput<S>>;
export function cli(
  command: string,
  options?: CliServerOptions,
): Source<unknown>;
export function cli(
  command: string,
  options: CliServerOptions = {},
): Source<unknown> {
  return new CliSourceAdapter(command, options);
}

/**
 * Writes route output to stdout.
 *
 * Strings are written as-is with a trailing newline. Objects and arrays are
 * pretty-printed as JSON. All other values are converted via `String()`.
 *
 * @returns A `Destination` that writes to `process.stdout`
 * @experimental
 */
cli.stdout = function (): Destination<unknown, void> {
  return new CliDestinationAdapter({ stream: "stdout" });
};

/**
 * Writes route output to stderr.
 *
 * Strings are written as-is with a trailing newline. Objects and arrays are
 * pretty-printed as JSON. All other values are converted via `String()`.
 *
 * @returns A `Destination` that writes to `process.stderr`
 * @experimental
 */
cli.stderr = function (): Destination<unknown, void> {
  return new CliDestinationAdapter({ stream: "stderr" });
};

// Re-export public types
export type {
  CliServerOptions,
  CliClientOptions,
  CliRouteMetadata,
  CliArgOptions,
  CliFlagOptions,
} from "./types.ts";

// Re-export store keys, discovery utilities, and parsing
export {
  ADAPTER_CLI_REGISTRY,
  isCliSource,
  getCliRegistry,
  parseFlags,
  extractJsonSchema,
} from "./shared.ts";

export { cliRunner } from "./runner.ts";
